version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: my-laravel-app
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            DB_HOST: db
            DB_DATABASE: my_database
            DB_USERNAME: my_user
            DB_PASSWORD: my_password
        volumes:
            - .:/var/www/html
        networks:
            - app-network

    db:
        image: mysql:8.0
        container_name: my-mysql-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: my_root_password
            MYSQL_DATABASE: my_database
            MYSQL_USER: my_user
            MYSQL_PASSWORD: my_password
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - app-network

volumes:
    mysql-data:

networks:
    app-network:
        driver: bridge
