version: "3"
services:
    app:
        image: registry.render.com/username/appname:latest
        deploy:
            replicas: 1
            restart_policy:
                condition: any
            resources:
                limits:
                    memory: 2G
        ports:
            - "80:80"
        environment:
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: study-tracer
            DB_USERNAME: sds
            DB_PASSWORD: secret
            REDIS_HOST: redis
            REDIS_PASSWORD: redis_password
        depends_on:
            - db
            - redis
    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: study-tracer
            MYSQL_USER: sds
            MYSQL_PASSWORD: secret
        volumes:
            - db-data:/var/lib/mysql
    redis:
        image: redis:alpine
        command: redis-server --requirepass redis_password
volumes:
    db-data:
